In this project, I'll analyze Lichess Games data from kaggle

In [5]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
print("Setup Complete")

Setup Complete

In [6]:
games_data = pd.read_csv('./input/games.csv', index_col='id')

In [21]:
games_data.head()

,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,rating_difference
id,,,,,,,,,,,,,,
TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,309
l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,61
mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,-4
kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,-15
9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,54

In [8]:
games_data.describe()

,created_at,last_move_at,turns,white_rating,black_rating,opening_ply
count,2.005800e+04,2.005800e+04,20058.000000,20058.000000,20058.000000,20058.000000
mean,1.483617e+12,1.483618e+12,60.465999,1596.631868,1588.831987,4.816981
std,2.850151e+10,2.850140e+10,33.570585,291.253376,291.036126,2.797152
min,1.376772e+12,1.376772e+12,1.000000,784.000000,789.000000,1.000000
25%,1.477548e+12,1.477548e+12,37.000000,1398.000000,1391.000000,3.000000
50%,1.496010e+12,1.496010e+12,55.000000,1567.000000,1562.000000,4.000000
75%,1.503170e+12,1.503170e+12,79.000000,1793.000000,1784.000000,6.000000
max,1.504493e+12,1.504494e+12,349.000000,2700.000000,2723.000000,28.000000

In [9]:
games_data.columns

Index(['rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='str')

In [10]:
games_data['created_at'] = pd.to_datetime(games_data['created_at'], unit='ms')

In [11]:
games_data['last_move_at'] = pd.to_datetime(games_data['last_move_at'], unit='ms')

In [12]:
games_data.isnull().sum()

rated             0
created_at        0
last_move_at      0
turns             0
victory_status    0
winner            0
increment_code    0
white_id          0
white_rating      0
black_id          0
black_rating      0
moves             0
opening_eco       0
opening_name      0
opening_ply       0
dtype: int64

In [13]:
games_data = games_data.drop(columns=['created_at', 'last_move_at'])

In [14]:
games_data['winner'].value_counts(normalize=True)#normalize tells percentage

winner
white    0.498604
black    0.454033
draw     0.047363
Name: proportion, dtype: float64

In [15]:
games_data['opening_name'].value_counts().head(10)

opening_name
Van't Kruijs Opening                             368
Sicilian Defense                                 358
Sicilian Defense: Bowdler Attack                 296
French Defense: Knight Variation                 271
Scotch Game                                      271
Scandinavian Defense: Mieses-Kotroc Variation    259
Queen's Pawn Game: Mason Attack                  232
Queen's Pawn Game: Chigorin Variation            229
Scandinavian Defense                             223
Horwitz Defense                                  209
Name: count, dtype: int64

In [16]:
games_data['opening_name'].unique()

<StringArray>
[                                    'Slav Defense: Exchange Variation',
                               'Nimzowitsch Defense: Kennedy Variation',
                                'King's Pawn Game: Leonardis Variation',
                               'Queen's Pawn Game: Zukertort Variation',
                                                     'Philidor Defense',
                                 'Sicilian Defense: Mongoose Variation',
                           'Blackmar-Diemer Gambit: Pietrowsky Defense',
    'Nimzowitsch Defense: Kennedy Variation |  Linksspringer Variation',
                                'Italian Game: Schilling-Kostic Gambit',
                        'Scandinavian Defense: Mieses-Kotroc Variation',
 ...
               'Queen's Gambit Refused: Baltic Defense |  Queen Attack',
          'King's Indian Defense: Orthodox Variation |  Bayonet Attack',
              'King's Gambit |  Falkbeer Countergambit |  Miles Gambit',
                                         'Ruy Lopez: Closed |  7...O-O',
         'Sicilian Defense: Najdorf Variation |  Neo-Classical Defense',
           'Sicilian Defense: Scheveningen Variation |  English Attack',
                  'Pirc Defense: Austrian Attack |  Kurajica Variation',
 'Queen's Indian Defense: Classical Variation |  Traditional Variation',
                     'Queen's Gambit Declined: Slav |  Dutch Variation',
         'Sicilian Defense: Najdorf Variation |  Polugaevsky Variation']
Length: 1477, dtype: str

In [17]:
games_data['rating_difference'] = games_data['white_rating'] - games_data['black_rating']

In [18]:
games_data.head()

,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,rating_difference
id,,,,,,,,,,,,,,
TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,309
l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,61
mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,-4
kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,-15
9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,54

In [19]:
games_data.groupby('winner')['rating_difference'].mean()

winner
black   -88.981113
draw     14.348421
white    95.307469
Name: rating_difference, dtype: float64

Doing an analysis on which opening(top 50) leads to more wins for white and black

In [28]:
top_openings = games_data['opening_name'].value_counts().head(50)
top_openings

opening_name
Van't Kruijs Opening                             368
Sicilian Defense                                 358
Sicilian Defense: Bowdler Attack                 296
French Defense: Knight Variation                 271
Scotch Game                                      271
Scandinavian Defense: Mieses-Kotroc Variation    259
Queen's Pawn Game: Mason Attack                  232
Queen's Pawn Game: Chigorin Variation            229
Scandinavian Defense                             223
Horwitz Defense                                  209
Caro-Kann Defense                                199
Philidor Defense #3                              198
Philidor Defense #2                              193
Indian Game                                      181
Italian Game: Anti-Fried Liver Defense           180
Four Knights Game: Italian Variation             176
Modern Defense                                   174
Owen Defense                                     168
King's Pawn Game: Wayward Queen Attack           164
Sicilian Defense: Old Sicilian                   159
King's Pawn Game: Leonardis Variation            154
Queen's Pawn Game                                142
Philidor Defense                                 135
Ruy Lopez: Steinitz Defense                      134
Hungarian Opening                                130
French Defense: Normal Variation                 129
Queen's Pawn                                     129
Bishop's Opening                                 128
Queen's Gambit Refused: Marshall Defense         127
Queen's Pawn Game #2                             118
Queen's Gambit Declined                          116
Queen's Pawn Game: Zukertort Variation           114
Queen's Gambit Accepted: Old Variation           111
French Defense: Exchange Variation               109
Italian Game                                     109
Sicilian Defense: Smith-Morra Gambit #2          108
Giuoco Piano                                     108
Pirc Defense #4                                  107
French Defense #2                                106
King's Pawn Game: McConnell Defense              100
English Opening: King's English Variation         98
Bishop's Opening: Berlin Defense                  94
Three Knights Opening                             88
King's Knight Opening                             87
Russian Game: Three Knights Game                  85
King's Knight Opening: Normal Variation           84
Queen's Pawn Game: London System                  79
King's Pawn Game: Damiano Defense                 79
Bird Opening                                      77
Mieses Opening                                    77
Name: count, dtype: int64

In [50]:
opening_data = games_data[['opening_name','winner']][games_data['opening_name'].isin(top_openings.index)]
opening_data

                                           opening_name winner
id
mIICvQHh          King's Pawn Game: Leonardis Variation  white
kWKvrqYL         Queen's Pawn Game: Zukertort Variation  white
9tXo1AUZ                               Philidor Defense  white
afoMwnLg  Scandinavian Defense: Mieses-Kotroc Variation  white
HgKLWPsz                           Van't Kruijs Opening  white
...                                                 ...    ...
nYOvevdh      English Opening: King's English Variation  white
uMzb0TPC               French Defense: Knight Variation  black
WSJDhbPl                                   Queen's Pawn  black
yrAas0Kj                Queen's Pawn Game: Mason Attack  white
N8G2JHGG                Queen's Pawn Game: Mason Attack  black

[7770 rows x 2 columns]

Using unstack() to calculate opening rates from opening data

In [54]:
opening_rates = opening_data.groupby('opening_name')['winner'].value_counts(normalize=True).unstack()
opening_rates

winner                                            black      draw     white
opening_name
Bird Opening                                   0.558442  0.051948  0.389610
Bishop's Opening                               0.398438  0.062500  0.539062
Bishop's Opening: Berlin Defense               0.329787  0.031915  0.638298
Caro-Kann Defense                              0.417085  0.035176  0.547739
English Opening: King's English Variation      0.397959  0.030612  0.571429
Four Knights Game: Italian Variation           0.420455  0.039773  0.539773
French Defense #2                              0.500000  0.047170  0.452830
French Defense: Exchange Variation             0.385321  0.082569  0.532110
French Defense: Knight Variation               0.446494  0.055351  0.498155
French Defense: Normal Variation               0.379845  0.031008  0.589147
Giuoco Piano                                   0.518519  0.055556  0.425926
Horwitz Defense                                0.449761  0.023923  0.526316
Hungarian Opening                              0.507692  0.023077  0.469231
Indian Game                                    0.552486  0.066298  0.381215
Italian Game                                   0.321101  0.110092  0.568807
Italian Game: Anti-Fried Liver Defense         0.405556  0.055556  0.538889
King's Knight Opening                          0.298851  0.011494  0.689655
King's Knight Opening: Normal Variation        0.488095  0.035714  0.476190
King's Pawn Game: Damiano Defense              0.367089  0.050633  0.582278
King's Pawn Game: Leonardis Variation          0.538961  0.025974  0.435065
King's Pawn Game: McConnell Defense            0.500000  0.040000  0.460000
King's Pawn Game: Wayward Queen Attack         0.512195  0.036585  0.451220
Mieses Opening                                 0.571429  0.012987  0.415584
Modern Defense                                 0.500000  0.034483  0.465517
Owen Defense                                   0.494048  0.053571  0.452381
Philidor Defense                               0.311111  0.066667  0.622222
Philidor Defense #2                            0.497409  0.041451  0.461140
Philidor Defense #3                            0.338384  0.020202  0.641414
Pirc Defense #4                                0.336449  0.074766  0.588785
Queen's Gambit Accepted: Old Variation         0.405405  0.036036  0.558559
Queen's Gambit Declined                        0.387931  0.017241  0.594828
Queen's Gambit Refused: Marshall Defense       0.322835  0.015748  0.661417
Queen's Pawn                                   0.302326  0.038760  0.658915
Queen's Pawn Game                              0.584507  0.042254  0.373239
Queen's Pawn Game #2                           0.491525  0.059322  0.449153
Queen's Pawn Game: Chigorin Variation          0.475983  0.034934  0.489083
Queen's Pawn Game: London System               0.531646  0.025316  0.443038
Queen's Pawn Game: Mason Attack                0.443966  0.056034  0.500000
Queen's Pawn Game: Zukertort Variation         0.385965  0.061404  0.552632
Russian Game: Three Knights Game               0.341176  0.035294  0.623529
Ruy Lopez: Steinitz Defense                    0.455224  0.044776  0.500000
Scandinavian Defense                           0.551570  0.044843  0.403587
Scandinavian Defense: Mieses-Kotroc Variation  0.343629  0.023166  0.633205
Scotch Game                                    0.424354  0.040590  0.535055
Sicilian Defense                               0.541899  0.041899  0.416201
Sicilian Defense: Bowdler Attack               0.554054  0.043919  0.402027
Sicilian Defense: Old Sicilian                 0.584906  0.037736  0.377358
Sicilian Defense: Smith-Morra Gambit #2        0.453704  0.055556  0.490741
Three Knights Opening                          0.409091  0.045455  0.545455
Van't Kruijs Opening                           0.614130  0.043478  0.342391

Getting best opening for white and black

In [58]:
best_opening_for_white = opening_rates.index[opening_rates['white'] == opening_rates['white'].max()]
best_opening_for_white

Index(['King's Knight Opening'], dtype='str', name='opening_name')

In [59]:
best_opening_for_black = opening_rates.index[opening_rates['black'] == opening_rates['black'].max()]
best_opening_for_black

Index(['Van't Kruijs Opening'], dtype='str', name='opening_name')

The best opening for white is King's Knight Opening and for black is Van't Kruijs Opening